// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalSolutionApplication.Data;

namespace UniversalSolutionApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240824122108_UserEmailNotNullFix")]
    partial class UserEmailNotNullFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionCombination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DimHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DimHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Id" }, "DimCombIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "DimHeaderId", "DimHeaderUserId" }, "DimHeaderIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "ItemId", "ItemUserId" }, "ItemIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("DimensionCombination");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DimensionGroup");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimGroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ListHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ListHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableType")
                        .HasColumnType("int");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("DimGroupId", "DimGroupUserId");

                    b.HasIndex("ListHeaderId", "ListHeaderUserId");

                    b.HasIndex(new[] { "Id", "UserId" }, "DimHeaderIdx")
                        .IsUnique()
                        .HasDatabaseName("DimHeaderIdx1");

                    b.HasIndex(new[] { "LinkHeaderId", "LinkHeaderUserId" }, "LinkDimHeaderIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "ListHeaderId" }, "ListIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("DimensionHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.Property<Guid>("DimensionHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("LineNum")
                        .HasPrecision(20, 2)
                        .HasColumnType("real(20)");

                    b.Property<Guid>("DimHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Bool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Double")
                        .HasPrecision(15, 2)
                        .HasColumnType("float(15)");

                    b.Property<int?>("Integer")
                        .HasColumnType("int");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimensionHeaderId", "LineNum", "DimHeaderUserId");

                    b.HasAlternateKey("LotId");

                    b.HasIndex(new[] { "DimensionHeaderId", "DimHeaderUserId" }, "DimHeaderIdx")
                        .HasDatabaseName("DimHeaderIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.HasIndex(new[] { "ItemId", "ItemUserId" }, "ItemIdx")
                        .HasDatabaseName("ItemIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId", "LineNum", "DimensionHeaderId" });

                    b.HasIndex(new[] { "DimensionHeaderId", "LineNum", "DimHeaderUserId" }, "LineNumIdx")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.ToTable("DimensionLine");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Follower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowerRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserRefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "FollowerIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "FollowerRefId" }, "FollowerRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "UserRefId" }, "UserRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("Follower");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ItemGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemGroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkItemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModuleUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("ItemGroupId", "ItemGroupUserId");

                    b.HasIndex("ModuleId", "ModuleUserId");

                    b.HasIndex(new[] { "ItemGroupId" }, "ItemGroupIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId", "Name" });

                    b.HasIndex(new[] { "Id", "UserId" }, "ItemIdx")
                        .IsUnique()
                        .HasDatabaseName("ItemIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "ItemGroupId", "ModuleId", "Name" });

                    b.HasIndex(new[] { "LinkItemId", "LinkItemUserId" }, "LinkItemIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ItemGroupId", "ModuleId", "Name" });

                    b.HasIndex(new[] { "ModuleId" }, "ModuleIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ItemGroupId", "Name" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "ItemGroupId", "ModuleId", "Name" });

                    b.ToTable("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkItemGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkItemGroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("LinkItemGroupId", "LinkItemGroupUserId");

                    b.HasIndex(new[] { "Id", "UserId" }, "ItemGroupIdx")
                        .IsUnique()
                        .HasDatabaseName("ItemGroupIdx1");

                    b.HasIndex(new[] { "LinkItemGroupId" }, "LinkItemGroupIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("ItemGroup");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.LinkedFormattingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionLineDimHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionLineLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterLinkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormattingType")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransLinkName")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransLinkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("DimensionLineLotId", "DimensionLineDimHeaderUserId");

                    b.HasIndex("TransLinkId", "TransLinkUserId");

                    b.ToTable("LinkedFormattingEntity");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListFormattingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ListFormattingEntity");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FilterRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterRefName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FilterRefUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkListHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkListHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id", "UserId");

                    b.HasIndex(new[] { "FilterRefId", "FilterRefUserId" }, "DimHeaderRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "FilterRefId", "FilterRefUserId" }, "ItemGroupRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "LinkListHeaderId", "LinkListHeaderUserId" }, "LinkListHeaderIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "Id", "UserId" }, "ListHeaderIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "ModuleId", "ModuleUserId" }, "ModuleIdx")
                        .HasDatabaseName("ModuleIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "FilterRefId", "FilterRefUserId" }, "ModuleRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx3")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "ModuleId" });

                    b.ToTable("ListHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListLine", b =>
                {
                    b.Property<Guid>("ListHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("LineNum")
                        .HasPrecision(20, 2)
                        .HasColumnType("real(20)");

                    b.Property<Guid>("ListHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ListHeaderId", "LineNum", "ListHeaderUserId");

                    b.HasAlternateKey("LotId");

                    b.HasIndex(new[] { "ItemId", "ItemUserId" }, "ItemIdx")
                        .HasDatabaseName("ItemIdx3")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId", "LineNum", "ListHeaderId" });

                    b.HasIndex(new[] { "ListHeaderId", "LineNum", "ListHeaderUserId" }, "LineNumIdx")
                        .IsUnique()
                        .HasDatabaseName("LineNumIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.HasIndex(new[] { "ListHeaderId", "ListHeaderUserId" }, "ListHeaderIdx")
                        .HasDatabaseName("ListHeaderIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.ToTable("ListLine");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FilterLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FilterLinkName")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FilterLinkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("General")
                        .HasColumnType("bit");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkModuleUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModuleRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModuleRefUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex(new[] { "FilterLinkId", "FilterLinkUserId", "FilterLinkName" }, "FilterLinkIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "LinkModuleId", "LinkModuleUserId" }, "LinkModuleIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "Id", "UserId" }, "ModuleIdx")
                        .IsUnique()
                        .HasDatabaseName("ModuleIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "Name" });

                    b.HasIndex(new[] { "ModuleRefId", "ModuleRefUserId" }, "ModuleRefIdx")
                        .HasDatabaseName("ModuleRefIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx4")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "Name" });

                    b.ToTable("Module");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.TextFormattingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TextFormattingEntity");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NickName" }, "NickNameIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "UserIdx")
                        .IsUnique()
                        .HasDatabaseName("UserIdx5")
                        .HasAnnotation("SqlServer:Include", new[] { "NickName", "Name", "Surname", "Email" });

                    b.ToTable("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.UserTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionCombinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionCombinationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionGroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionLineDimHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DimensionLineDimensionHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("DimensionLineLineNum")
                        .HasColumnType("real(20)");

                    b.Property<Guid?>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemGroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkedFormattingEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkedFormattingEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ListFormattingEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ListFormattingEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("ListLineLineNum")
                        .HasColumnType("real(20)");

                    b.Property<Guid?>("ListLineListHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ListLineListHeaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RefType")
                        .HasColumnType("int");

                    b.Property<string>("SurrogateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TextFormattingEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TextFormattingEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransLinkName")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransLinkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("DimensionCombinationId", "DimensionCombinationUserId");

                    b.HasIndex("DimensionGroupId", "DimensionGroupUserId");

                    b.HasIndex("DimensionHeaderId", "DimensionHeaderUserId");

                    b.HasIndex("ItemGroupId", "ItemGroupUserId");

                    b.HasIndex("LinkedFormattingEntityId", "LinkedFormattingEntityUserId");

                    b.HasIndex("ListFormattingEntityId", "ListFormattingEntityUserId");

                    b.HasIndex("TextFormattingEntityId", "TextFormattingEntityUserId");

                    b.HasIndex("DimensionLineDimensionHeaderId", "DimensionLineLineNum", "DimensionLineDimHeaderUserId");

                    b.HasIndex("ListLineListHeaderId", "ListLineLineNum", "ListLineListHeaderUserId");

                    b.HasIndex(new[] { "Id", "UserId" }, "TransIdx")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Include", new[] { "TransType" });

                    b.HasIndex(new[] { "TransLinkId", "TransLinkUserId", "TransLinkName" }, "TransLinkIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx6")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("UserTransaction");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionCombination", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeader")
                        .WithMany("DimCombs")
                        .HasForeignKey("DimHeaderId", "DimHeaderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("DimCombs")
                        .HasForeignKey("ItemId", "ItemUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DimHeader");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionGroup", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("DimensionGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("DimensionHeaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionGroup", "DimensionGroup")
                        .WithMany("DimHeaders")
                        .HasForeignKey("DimGroupId", "DimGroupUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "LinkHeader")
                        .WithMany("LinkDimHeaders")
                        .HasForeignKey("LinkHeaderId", "LinkHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("DimHeaders")
                        .HasForeignKey("ListHeaderId", "ListHeaderUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DimensionGroup");

                    b.Navigation("LinkHeader");

                    b.Navigation("ListHeader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimensionHeader")
                        .WithMany("Lines")
                        .HasForeignKey("DimensionHeaderId", "DimHeaderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("DimLines")
                        .HasForeignKey("ItemId", "ItemUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DimensionHeader");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Follower", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "FollowerRef")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerRefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.User", "UserRef")
                        .WithMany("UserRefs")
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowerRef");

                    b.Navigation("UserRef");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId", "ItemGroupUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.Item", "LinkItem")
                        .WithMany("LinkItems")
                        .HasForeignKey("LinkItemId", "LinkItemUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("Items")
                        .HasForeignKey("ModuleId", "ModuleUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ItemGroup");

                    b.Navigation("LinkItem");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ItemGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "LinkItemGroup")
                        .WithMany("LinkItemGroups")
                        .HasForeignKey("LinkItemGroupId", "LinkItemGroupUserId");

                    b.Navigation("LinkItemGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.LinkedFormattingEntity", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("LinkedFormattingEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionLine", "DimensionLine")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("DimensionLineLotId", "DimensionLineDimHeaderUserId")
                        .HasPrincipalKey("LotId", "DimHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.DimensionGroup", "DimensionGroup")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimensionHeader")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ListFormattingEntity", "ListFormattingEntity")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.HasOne("UniversalSolutionApplication.Models.TextFormattingEntity", "TextFormattingEntity")
                        .WithMany("LinkedFormattingEntities")
                        .HasForeignKey("TransLinkId", "TransLinkUserId");

                    b.Navigation("DimensionGroup");

                    b.Navigation("DimensionHeader");

                    b.Navigation("DimensionLine");

                    b.Navigation("Item");

                    b.Navigation("ItemGroup");

                    b.Navigation("ListFormattingEntity");

                    b.Navigation("ListHeader");

                    b.Navigation("Module");

                    b.Navigation("TextFormattingEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListFormattingEntity", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ListFormattingEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ListHeaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeaderRef")
                        .WithMany("ListHeaderRefs")
                        .HasForeignKey("FilterRefId", "FilterRefUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroupRef")
                        .WithMany("ListHeaderRefs")
                        .HasForeignKey("FilterRefId", "FilterRefUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.Module", "ModuleRef")
                        .WithMany("ListHeaderRefs")
                        .HasForeignKey("FilterRefId", "FilterRefUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "LinkListHeader")
                        .WithMany("LinkListHeaders")
                        .HasForeignKey("LinkListHeaderId", "LinkListHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("ListHeaders")
                        .HasForeignKey("ModuleId", "ModuleUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DimHeaderRef");

                    b.Navigation("ItemGroupRef");

                    b.Navigation("LinkListHeader");

                    b.Navigation("Module");

                    b.Navigation("ModuleRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListLine", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("ListLines")
                        .HasForeignKey("ItemId", "ItemUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("Lines")
                        .HasForeignKey("ListHeaderId", "ListHeaderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ListHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeader")
                        .WithMany("Modules")
                        .HasForeignKey("FilterLinkId", "FilterLinkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("Modules")
                        .HasForeignKey("FilterLinkId", "FilterLinkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.Module", "LinkModule")
                        .WithMany("LinkModules")
                        .HasForeignKey("LinkModuleId", "LinkModuleUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "ModuleRef")
                        .WithMany("ModuleRefs")
                        .HasForeignKey("ModuleRefId", "ModuleRefUserId");

                    b.Navigation("DimHeader");

                    b.Navigation("ItemGroup");

                    b.Navigation("LinkModule");

                    b.Navigation("ModuleRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.TextFormattingEntity", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("TextFormattingEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.UserTransaction", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.Follower", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId");

                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Trans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionCombination", "DimensionCombination")
                        .WithMany()
                        .HasForeignKey("DimensionCombinationId", "DimensionCombinationUserId");

                    b.HasOne("UniversalSolutionApplication.Models.DimensionGroup", "DimensionGroup")
                        .WithMany()
                        .HasForeignKey("DimensionGroupId", "DimensionGroupUserId");

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimensionHeader")
                        .WithMany()
                        .HasForeignKey("DimensionHeaderId", "DimensionHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId", "ItemGroupUserId");

                    b.HasOne("UniversalSolutionApplication.Models.LinkedFormattingEntity", "LinkedFormattingEntity")
                        .WithMany()
                        .HasForeignKey("LinkedFormattingEntityId", "LinkedFormattingEntityUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ListFormattingEntity", "ListFormattingEntity")
                        .WithMany()
                        .HasForeignKey("ListFormattingEntityId", "ListFormattingEntityUserId");

                    b.HasOne("UniversalSolutionApplication.Models.TextFormattingEntity", "TextFormattingEntity")
                        .WithMany()
                        .HasForeignKey("TextFormattingEntityId", "TextFormattingEntityUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("Trans")
                        .HasForeignKey("TransLinkId", "TransLinkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("Trans")
                        .HasForeignKey("TransLinkId", "TransLinkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("Trans")
                        .HasForeignKey("TransLinkId", "TransLinkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversalSolutionApplication.Models.DimensionLine", "DimensionLine")
                        .WithMany()
                        .HasForeignKey("DimensionLineDimensionHeaderId", "DimensionLineLineNum", "DimensionLineDimHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ListLine", "ListLine")
                        .WithMany()
                        .HasForeignKey("ListLineListHeaderId", "ListLineLineNum", "ListLineListHeaderUserId");

                    b.Navigation("DimensionCombination");

                    b.Navigation("DimensionGroup");

                    b.Navigation("DimensionHeader");

                    b.Navigation("DimensionLine");

                    b.Navigation("Follower");

                    b.Navigation("Item");

                    b.Navigation("ItemGroup");

                    b.Navigation("LinkedFormattingEntity");

                    b.Navigation("ListFormattingEntity");

                    b.Navigation("ListHeader");

                    b.Navigation("ListLine");

                    b.Navigation("Module");

                    b.Navigation("TextFormattingEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionGroup", b =>
                {
                    b.Navigation("DimHeaders");

                    b.Navigation("LinkedFormattingEntities");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.Navigation("DimCombs");

                    b.Navigation("Lines");

                    b.Navigation("LinkDimHeaders");

                    b.Navigation("LinkedFormattingEntities");

                    b.Navigation("ListHeaderRefs");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.Navigation("LinkedFormattingEntities");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.Navigation("DimCombs");

                    b.Navigation("DimLines");

                    b.Navigation("LinkedFormattingEntities");

                    b.Navigation("LinkItems");

                    b.Navigation("ListLines");

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LinkedFormattingEntities");

                    b.Navigation("LinkItemGroups");

                    b.Navigation("ListHeaderRefs");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListFormattingEntity", b =>
                {
                    b.Navigation("LinkedFormattingEntities");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.Navigation("DimHeaders");

                    b.Navigation("Lines");

                    b.Navigation("LinkedFormattingEntities");

                    b.Navigation("LinkListHeaders");

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LinkedFormattingEntities");

                    b.Navigation("LinkModules");

                    b.Navigation("ListHeaderRefs");

                    b.Navigation("ListHeaders");

                    b.Navigation("ModuleRefs");

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.TextFormattingEntity", b =>
                {
                    b.Navigation("LinkedFormattingEntities");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.User", b =>
                {
                    b.Navigation("DimensionGroups");

                    b.Navigation("DimensionHeaders");

                    b.Navigation("Followers");

                    b.Navigation("ItemGroups");

                    b.Navigation("Items");

                    b.Navigation("LinkedFormattingEntity");

                    b.Navigation("ListFormattingEntity");

                    b.Navigation("ListHeaders");

                    b.Navigation("Modules");

                    b.Navigation("TextFormattingEntity");

                    b.Navigation("Trans");

                    b.Navigation("UserRefs");
                });
#pragma warning restore 612, 618
        }
    }
}
