// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalSolutionApplication.Data;

namespace UniversalSolutionApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240424213214_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionCombination", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DimHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DimHeaderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Id" }, "DimCombIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "DimHeaderId", "DimHeaderUserId" }, "DimHeaderIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "ItemId", "ItemUserId" }, "ItemIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("DimensionCombination");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<string>("LinkHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkHeaderUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ListHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ListHeaderUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("TableType")
                        .HasColumnType("int");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("ListHeaderId", "ListHeaderUserId");

                    b.HasIndex(new[] { "Id", "UserId" }, "DimHeaderIdx")
                        .IsUnique()
                        .HasDatabaseName("DimHeaderIdx1");

                    b.HasIndex(new[] { "LinkHeaderId", "LinkHeaderUserId" }, "LinkDimHeaderIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "ListHeaderId" }, "ListIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("DimensionHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.Property<string>("DimensionHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("LineNum")
                        .HasPrecision(20, 2)
                        .HasColumnType("real(20)");

                    b.Property<string>("DimHeaderUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Bool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Double")
                        .HasPrecision(15, 2)
                        .HasColumnType("float(15)");

                    b.Property<int?>("Integer")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LotId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimensionHeaderId", "LineNum", "DimHeaderUserId");

                    b.HasAlternateKey("LotId");

                    b.HasIndex(new[] { "DimensionHeaderId", "DimHeaderUserId" }, "DimHeaderIdx")
                        .HasDatabaseName("DimHeaderIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.HasIndex(new[] { "ItemId", "ItemUserId" }, "ItemIdx")
                        .HasDatabaseName("ItemIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId", "LineNum", "DimensionHeaderId" });

                    b.HasIndex(new[] { "DimensionHeaderId", "LineNum", "DimHeaderUserId" }, "LineNumIdx")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.ToTable("DimensionLine");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Follower", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FollowerRefId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserRefId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "FollowerIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "FollowerRefId" }, "FollowerRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "UserRefId" }, "UserRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("Follower");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<string>("ItemGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemGroupUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<string>("LinkItemId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkItemUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("ItemGroupId", "ItemGroupUserId");

                    b.HasIndex("ModuleId", "ModuleUserId");

                    b.HasIndex(new[] { "ItemGroupId" }, "ItemGroupIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId", "Name" });

                    b.HasIndex(new[] { "Id", "UserId" }, "ItemIdx")
                        .IsUnique()
                        .HasDatabaseName("ItemIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "ItemGroupId", "ModuleId", "Name" });

                    b.HasIndex(new[] { "LinkItemId", "LinkItemUserId" }, "LinkItemIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ItemGroupId", "ModuleId", "Name" });

                    b.HasIndex(new[] { "ModuleId" }, "ModuleIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ItemGroupId", "Name" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "ItemGroupId", "ModuleId", "Name" });

                    b.ToTable("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<string>("LinkItemGroupId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkItemGroupUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("LinkItemGroupId", "LinkItemGroupUserId");

                    b.HasIndex(new[] { "Id", "UserId" }, "ItemGroupIdx")
                        .IsUnique()
                        .HasDatabaseName("ItemGroupIdx1");

                    b.HasIndex(new[] { "LinkItemGroupId" }, "LinkItemGroupIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("ItemGroup");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimHeaderRefId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DimHeaderRefUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<string>("ItemGroupRefId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemGroupRefUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<string>("LinkListHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkListHeaderUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleRefId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleRefUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id", "UserId");

                    b.HasIndex(new[] { "DimHeaderRefId", "DimHeaderRefUserId" }, "DimHeaderRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "ItemGroupRefId", "ItemGroupRefUserId" }, "ItemGroupRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "LinkListHeaderId", "LinkListHeaderUserId" }, "LinkListHeaderIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "Id", "UserId" }, "ListHeaderIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "ModuleId", "ModuleUserId" }, "ModuleIdx")
                        .HasDatabaseName("ModuleIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "ModuleRefId", "ModuleRefUserId" }, "ModuleRefIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId", "ModuleId" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx3")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "ModuleId" });

                    b.ToTable("ListHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListLine", b =>
                {
                    b.Property<string>("ListHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("LineNum")
                        .HasPrecision(20, 2)
                        .HasColumnType("real(20)");

                    b.Property<string>("ListHeaderUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LotId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ListHeaderId", "LineNum", "ListHeaderUserId");

                    b.HasAlternateKey("LotId");

                    b.HasIndex(new[] { "ItemId", "ItemUserId" }, "ItemIdx")
                        .HasDatabaseName("ItemIdx3")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId", "LineNum", "ListHeaderId" });

                    b.HasIndex(new[] { "ListHeaderId", "LineNum", "ListHeaderUserId" }, "LineNumIdx")
                        .IsUnique()
                        .HasDatabaseName("LineNumIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.HasIndex(new[] { "ListHeaderId", "ListHeaderUserId" }, "ListHeaderIdx")
                        .HasDatabaseName("ListHeaderIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "LotId" });

                    b.ToTable("ListLine");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DimHeaderUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<bool>("General")
                        .HasColumnType("bit");

                    b.Property<string>("ItemGroupId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemGroupUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<string>("LinkModuleId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkModuleUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleRefId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleRefUserId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "UserId");

                    b.HasIndex(new[] { "DimHeaderId", "DimHeaderUserId" }, "DimHeaderIdx")
                        .HasDatabaseName("DimHeaderIdx3")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "ItemGroupId", "ItemGroupUserId" }, "ItemGroupIdx")
                        .HasDatabaseName("ItemGroupIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "LinkModuleId", "LinkModuleUserId" }, "LinkModuleIdx")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "Id", "UserId" }, "ModuleIdx")
                        .IsUnique()
                        .HasDatabaseName("ModuleIdx2")
                        .HasAnnotation("SqlServer:Include", new[] { "Name" });

                    b.HasIndex(new[] { "ModuleRefId", "ModuleRefUserId" }, "ModuleRefIdx")
                        .HasDatabaseName("ModuleRefIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "UserId" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx4")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "Name" });

                    b.ToTable("Module");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NickName" }, "NickNameIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "UserIdx")
                        .IsUnique()
                        .HasDatabaseName("UserIdx5")
                        .HasAnnotation("SqlServer:Include", new[] { "NickName", "Name", "Surname", "Email" });

                    b.ToTable("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.UserTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ListId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RefType")
                        .HasColumnType("int");

                    b.Property<string>("TransLinkUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TransType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ItemId", "TransLinkUserId" }, "ItemIdx")
                        .HasDatabaseName("ItemIdx4")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "ListId", "TransLinkUserId" }, "ListIdx")
                        .HasDatabaseName("ListIdx1")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "ModuleId", "TransLinkUserId" }, "ModuleIdx")
                        .HasDatabaseName("ModuleIdx3")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.HasIndex(new[] { "Id", "UserId" }, "TransIdx")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Include", new[] { "TransType" });

                    b.HasIndex(new[] { "UserId" }, "UserIdx")
                        .HasDatabaseName("UserIdx6")
                        .HasAnnotation("SqlServer:Include", new[] { "Id" });

                    b.ToTable("UserTransaction");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionCombination", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeader")
                        .WithMany("DimCombs")
                        .HasForeignKey("DimHeaderId", "DimHeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("DimCombs")
                        .HasForeignKey("ItemId", "ItemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DimHeader");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("DimensionHeaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "LinkHeader")
                        .WithMany("LinkDimHeaders")
                        .HasForeignKey("LinkHeaderId", "LinkHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("DimHeaders")
                        .HasForeignKey("ListHeaderId", "ListHeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LinkHeader");

                    b.Navigation("ListHeader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimensionHeader")
                        .WithMany("Lines")
                        .HasForeignKey("DimensionHeaderId", "DimHeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("DimLines")
                        .HasForeignKey("ItemId", "ItemUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DimensionHeader");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Follower", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "FollowerRef")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.User", "UserRef")
                        .WithMany("UserRefs")
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowerRef");

                    b.Navigation("UserRef");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId", "ItemGroupUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "LinkItem")
                        .WithMany("LinkItems")
                        .HasForeignKey("LinkItemId", "LinkItemUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("Items")
                        .HasForeignKey("ModuleId", "ModuleUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ItemGroup");

                    b.Navigation("LinkItem");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ItemGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "LinkItemGroup")
                        .WithMany("LinkItemGroups")
                        .HasForeignKey("LinkItemGroupId", "LinkItemGroupUserId");

                    b.Navigation("LinkItemGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ListHeaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeaderRef")
                        .WithMany("ListHeaderRefs")
                        .HasForeignKey("DimHeaderRefId", "DimHeaderRefUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroupRef")
                        .WithMany("ListHeaderRefs")
                        .HasForeignKey("ItemGroupRefId", "ItemGroupRefUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "LinkListHeader")
                        .WithMany("LinkListHeaders")
                        .HasForeignKey("LinkListHeaderId", "LinkListHeaderUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("ListHeaders")
                        .HasForeignKey("ModuleId", "ModuleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Module", "ModuleRef")
                        .WithMany("ListHeaderRefs")
                        .HasForeignKey("ModuleRefId", "ModuleRefUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DimHeaderRef");

                    b.Navigation("ItemGroupRef");

                    b.Navigation("LinkListHeader");

                    b.Navigation("Module");

                    b.Navigation("ModuleRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListLine", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("ListLines")
                        .HasForeignKey("ItemId", "ItemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("Lines")
                        .HasForeignKey("ListHeaderId", "ListHeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ListHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeader")
                        .WithMany("Modules")
                        .HasForeignKey("DimHeaderId", "DimHeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("Modules")
                        .HasForeignKey("ItemGroupId", "ItemGroupUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversalSolutionApplication.Models.Module", "LinkModule")
                        .WithMany("LinkModules")
                        .HasForeignKey("LinkModuleId", "LinkModuleUserId");

                    b.HasOne("UniversalSolutionApplication.Models.Module", "ModuleRef")
                        .WithMany("ModuleRefs")
                        .HasForeignKey("ModuleRefId", "ModuleRefUserId");

                    b.Navigation("DimHeader");

                    b.Navigation("ItemGroup");

                    b.Navigation("LinkModule");

                    b.Navigation("ModuleRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.UserTransaction", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Trans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("Trans")
                        .HasForeignKey("ItemId", "TransLinkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "List")
                        .WithMany("Trans")
                        .HasForeignKey("ListId", "TransLinkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("Trans")
                        .HasForeignKey("ModuleId", "TransLinkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("List");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.Navigation("DimCombs");

                    b.Navigation("Lines");

                    b.Navigation("LinkDimHeaders");

                    b.Navigation("ListHeaderRefs");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.Navigation("DimCombs");

                    b.Navigation("DimLines");

                    b.Navigation("LinkItems");

                    b.Navigation("ListLines");

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LinkItemGroups");

                    b.Navigation("ListHeaderRefs");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.Navigation("DimHeaders");

                    b.Navigation("Lines");

                    b.Navigation("LinkListHeaders");

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LinkModules");

                    b.Navigation("ListHeaderRefs");

                    b.Navigation("ListHeaders");

                    b.Navigation("ModuleRefs");

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.User", b =>
                {
                    b.Navigation("DimensionHeaders");

                    b.Navigation("Followers");

                    b.Navigation("ItemGroups");

                    b.Navigation("Items");

                    b.Navigation("ListHeaders");

                    b.Navigation("Modules");

                    b.Navigation("Trans");

                    b.Navigation("UserRefs");
                });
#pragma warning restore 612, 618
        }
    }
}
