// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalSolutionApplication.Data;

namespace UniversalSolutionApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionCombination", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DimHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DimHeaderId");

                    b.HasIndex("ItemId");

                    b.ToTable("DimensionCombination");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("TableType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DimensionHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.Property<string>("DimensionHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("LineNum")
                        .HasPrecision(20, 2)
                        .HasColumnType("real(20)");

                    b.Property<bool?>("Bool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Double")
                        .HasPrecision(15, 2)
                        .HasColumnType("float(15)");

                    b.Property<int?>("Integer")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LotId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimensionHeaderId", "LineNum");

                    b.HasAlternateKey("LotId");

                    b.HasIndex("ItemId");

                    b.ToTable("DimensionLine");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ItemGroup");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleRefId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleRefId");

                    b.HasIndex("UserId");

                    b.ToTable("ListHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListLine", b =>
                {
                    b.Property<string>("ListHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("LineNum")
                        .HasPrecision(20, 2)
                        .HasColumnType("real(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LotId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ListHeaderId", "LineNum");

                    b.HasAlternateKey("LotId");

                    b.HasIndex("ItemId");

                    b.ToTable("ListLine");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimHeaderId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("General")
                        .HasColumnType("bit");

                    b.Property<string>("ItemGroupId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModuleRefId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DimHeaderId");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ModuleRefId");

                    b.HasIndex("UserId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.UserTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefType")
                        .HasColumnType("int");

                    b.Property<int>("TransType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTransaction");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionCombination", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeader")
                        .WithMany("DimCombs")
                        .HasForeignKey("DimHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("DimCombs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DimHeader");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("DimensionHeaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionLine", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimensionHeader")
                        .WithMany("Lines")
                        .HasForeignKey("DimensionHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("DimLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DimensionHeader");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany("Items")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemGroup");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ItemGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Module", "ModuleRef")
                        .WithMany()
                        .HasForeignKey("ModuleRefId");

                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("ListHeaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("ModuleRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListLine", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany("ListLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "ListHeader")
                        .WithMany("Lines")
                        .HasForeignKey("ListHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ListHeader");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.DimensionHeader", "DimHeader")
                        .WithMany()
                        .HasForeignKey("DimHeaderId");

                    b.HasOne("UniversalSolutionApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany("Modules")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversalSolutionApplication.Models.Module", "ModuleRef")
                        .WithMany()
                        .HasForeignKey("ModuleRefId");

                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimHeader");

                    b.Navigation("ItemGroup");

                    b.Navigation("ModuleRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.UserTransaction", b =>
                {
                    b.HasOne("UniversalSolutionApplication.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.ListHeader", "List")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalSolutionApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("List");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.DimensionHeader", b =>
                {
                    b.Navigation("DimCombs");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Item", b =>
                {
                    b.Navigation("DimCombs");

                    b.Navigation("DimLines");

                    b.Navigation("ListLines");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ItemGroup", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.ListHeader", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.Module", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UniversalSolutionApplication.Models.User", b =>
                {
                    b.Navigation("DimensionHeaders");

                    b.Navigation("ItemGroups");

                    b.Navigation("Items");

                    b.Navigation("ListHeaders");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
